<?xml version="1.0"?>
<package format="2">
    <name>pointcloud_merger</name>
    <version>0.0.1</version>
    <description>Merge 2 pointcloud2s into one</description>

    <maintainer email="thomas.simon@ensta-paris.com">Thomas SIMON</maintainer>
    <license>BSD</license>

    <buildtool_depend>colcon</buildtool_depend>

    <depend>message_filters</depend>
    <depend>rclcpp</depend>
    <depend>sensor_msgs</depend>
    <depend>rclcpp_components</depend>
    <depend>tf2</depend>
    <depend>tf2_ros</depend>
    <depend>tf2_sensor_msgs</depend>

    <export>
        <rclcpp_components plugin="${prefix}/pointcloud_merger.xml"/>
    </export>

</package>
